export const categoryCards = [
  {
    key: 'road',
    label: 'Road Damage',
    icon: '🛣',
    description: 'Potholes, cracks, and surface damage',
    gradient: 'from-sky-500 via-sky-400 to-cyan-400',
  },
  {
    key: 'water',
    label: 'Water Leakage',
    icon: '💧',
    description: 'Leaks, bursts, standing water',
    gradient: 'from-cyan-500 via-sky-400 to-sky-300',
  },
  {
    key: 'electricity',
    label: 'Electricity',
    icon: '⚡',
    description: 'Power outages and wiring faults',
    gradient: 'from-amber-500 via-orange-400 to-rose-400',
  },
  {
    key: 'garbage',
    label: 'Garbage',
    icon: '🗑',
    description: 'Waste collection and litter issues',
    gradient: 'from-emerald-500 via-lime-400 to-emerald-300',
  },
  {
    key: 'traffic',
    label: 'Traffic',
    icon: '🚦',
    description: 'Signal problems and congestion',
    gradient: 'from-fuchsia-500 via-pink-400 to-rose-400',
  },
  {
    key: 'parks',
    label: 'Parks',
    icon: '🌳',
    description: 'Green spaces and park maintenance',
    gradient: 'from-emerald-500 via-teal-400 to-sky-300',
  },
  {
    key: 'toilet',
    label: 'Public Toilets',
    icon: '🚽',
    description: 'Sanitation and restroom access',
    gradient: 'from-slate-500 via-zinc-400 to-slate-300',
  },
  {
    key: 'animal',
    label: 'Animal Issues',
    icon: '🐕',
    description: 'Stray animals and wildlife concerns',
    gradient: 'from-amber-500 via-orange-400 to-amber-300',
  },
  {
    key: 'pollution',
    label: 'Pollution',
    icon: '🏭',
    description: 'Air, noise, or chemical pollution',
    gradient: 'from-violet-500 via-fuchsia-400 to-pink-300',
  },
  {
    key: 'other',
    label: 'Other',
    icon: '➕',
    description: 'Any other civic matter',
    gradient: 'from-slate-500 via-slate-400 to-slate-300',
  },
];

export const initialForm = {
  category: '',
  location: {
    address: '',
    city: '',
    state: '',
    coordinates: { lat: '', lng: '' },
    landmark: '',
  },
  title: '',
  description: '',
  priority: 'medium',
  severity: 50,
  impact: 'Moderate community impact',
  detectedDate: '',
  detectedTime: '',
  anonymous: false,
  areaAffected: '',
  photos: [] as string[],
};
